#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# %% -------------------------------------------------------------------------

#%% Overview

"""
The code below generates the following list of figures and tables:
    
    Main Figures
    
    Fig 3: Results of Quantifying the Human Cost of War Analysis.
           
           It consists of the main subplots:
               
            - Fig 3A: A comparison of the total number of articles published by 
                      each news outlet compared to the subsets containing at 
                      least one CVN about Palestine and those with at least one 
                      CVN about Israel. 
                      
                      
           - Fig 3B: The weekly proportion of expected mentions allocated to 
                     the Palestinian side (∆Pn) based on the baseline model, 
                     shown for each news outlet.
                       
                     
           - Fig 3C: A bar plot displaying the total number of doubt-casting 
                     phrases per source, alongside additional charts breaking 
                     down the counts by the type of doubt-casting technique used 
                     by each outlet.
        
                                      
    Supplementary Figures
    
            Supp Fig 6: Disparity in casualty reporting across media sources.
                        
                        
            Supp Fig 7: Baseline comparison of the expected versus actual number 
                        of casualtyrelated CVN mentions for each news outlet 
                        over time. 
                        
                        
            Supp Fig 8: Proportion of Articles Reporting Child-Related CVNs by 
                        Side and Media Source. 
                  

            Supp Fig 9: Proportion of Articles Reporting Child-Related CVNs by 
                        Side and Media Source for Casualties-related CVNs only.
                        
            
            Supp Fig 15: Figure shows the weekly share of CVN statements 
                         published in 2023/24 that had Casting Doubt phrases in 
                         terms of Source Doubting and Uncertainty in Numbers.
            
    
    Supplementary Tables
    
            Supp Tab 6: Distribution of Civilian Victim Numbers (CVNs) by Type 
                        for Palestine and Israel across the four Media Outlets. 
                        
                        
            Supp Tab 9: Percentage of CVNs Reported with References Across Media 
                        Sources and Sides
                        

            Supp Tab 10: Final List of Doubt-Casting Phrases and Their Categories. 
                         (not generated by code as it is manually entered but 
                          used by supp tables 11 to 14)                             
                             
            Supp Tab 11-14: Breakdown of Doubt-Casting Phrases in Casualty 
                            Reporting Sentences in {source}.
                             
                            
            Supp Tab 15:  Child-related Mentions in Media Coverage of Palestine 
                          and Israel: Counts and Percentages Across Four Outlets 
                          (with baseline reference)
                         
                         
"""


#labels_dict.Label.value_counts()


# %% -------------------------------------------------------------------------

# %%Initialization

# %%Import Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import interpolate
from datetime import datetime, timedelta
import matplotlib.dates as mdates
#import os
#import ast
#from datetime import date


# %% Switches


run_validation = False


# Plot Style Input
dpi = 300

sns.set_theme(rc={"figure.dpi": dpi})

sns.set(style='white')



# %% Constants

dict_sources = { "Al Jazeera English":"AJE", 
                "BBC":"BBC",
                "CNN Wire": "CNN", 
                "The New York Times":"NYT" }
     


news_sources   = ['AJE', 'BBC', 'CNN', 'NYT']



# %% Paths

# Primary Data
path_primary_data           = '01- Primary Data/df_primary.csv'


# Response Data
path_cvn_resp               = '03- LLM Response Data/Response Data - CVN Instances.csv'

path_cvn_cited_source_resp  = "03- LLM Response Data/Response Data - CVN Instances - Cited Sources.xlsx"


# Aggregated Data
path_past_conflict_agg_data = "04- Past Conflict Aggregated Data/"


# Secondary
path_plot_colors            = "02- Secondary Data/02- Project Plotting Colors.xlsx"

path_critical_events        = "02- Secondary Data/03- Conflict Events.xlsx"

stat_label_categ_path       = '02- Secondary Data/04- Statistics Labels Categories.xlsx'

path_actual_casualties      = '02- Secondary Data/06- Actual Reported Casualties.csv'

cd_phrases_path             = '02- Secondary Data/05- CVN - Casting Doubt - Critical Phrases.xlsx'

path_wip                    = '02- Secondary Data/01- Work in progress/'


# Report Plots and Tables Container
path_report                 = "05- Report Plots and Tables/"




# %% -------------------------------------------------------------------------

# %% IMPORT DATA
print("\nImporting Data")

# %% -------------------------------------------------------------------------

# %% Colors

dict_colors = pd.read_excel(path_plot_colors, usecols = ["Entity","Color"])

dict_colors = dict_colors.dropna().set_index('Entity')['Color'].to_dict()


# %%  Events

# Import Critical Events

# -  read the excel containing the events data
df_events = pd.read_excel(path_critical_events, sheet_name = "Final_List")

# -  convert dates from str to datetime & extract dates only
df_events['Date'] = pd.to_datetime(df_events['Date'], format = "%Y-%m-%d").copy()

df_events['Date'] = df_events['Date'].dt.date


# -  convert dates from str to datetime & extract dates only
df_events['Label_Date'] = pd.to_datetime(df_events['Label_Date'], format = "%Y-%m-%d").copy()

df_events['Label_Date'] = df_events['Label_Date'].dt.date

# -  remove any white spaces before or after the caption labels of v lines
df_events['Caption'] = df_events['Caption'].str.strip()

# -  filter events by source list
filter_event_src = df_events['Source List']!='Manually Collected'

df_events = df_events[filter_event_src].copy()


df_events = df_events.fillna("").copy()


# %% LN + BBC

# Import article_num, source, date

df_primary = pd.read_csv(path_primary_data)

df_primary = df_primary.reset_index(drop=True)

if "Unnamed: 0" in df_primary.columns:
    df_primary = df_primary.drop(["Unnamed: 0"], axis=1)

# Convert the date column from string to datetime
df_primary['Date'] = pd.to_datetime(df_primary['Date'], format = "%d %B %Y").copy()



# %% CVN Response Data

df_cs = pd.read_csv(path_cvn_resp)

df_cs = df_cs.reset_index(drop=True)

df_cs['Date'] = pd.to_datetime(df_cs['Date'], format = "%Y-%m-%d").copy()


# %% -------------------------------------------------------------------------
# %% FIGURES & TABLES
# %% -------------------------------------------------------------------------

# %%   Supp Fig 6: Percent Diff - Lineplots

print("\nGenerating Supp Fig 6")

# The code below simply generates a main plots of 4 lineplots for each source
# The lineplots show the percentage difference in articles referencing Palestinian 
# and Israeli casualties over the first 12 months, with major events impacting
# each side marked in green (Palestinian) and blue (Israeli).



# [1] Code for a plot-smoothing function that will be used later when generating
#     Supp Fig 6. It takes in Date-indexed data and produces an interpolated 
#     output based on the indicated smoothness resolution as shown by the res 
#     parameter

def smooth_plot (data, res = 1000):

    smoothed_data = pd.DataFrame({'Date':[]})

    for col in data:

        temp_df = data[col].copy()
        temp_df = temp_df.dropna()
        dates = temp_df.index
        dates = dates.astype('datetime64[s]').astype(np.int64)
        
        x = dates
        y = temp_df.to_list()
        interp_fn = interpolate.interp1d(x, y, kind='cubic')

        xnew = np.arange(dates[0], dates[-1], res)
        ynew = interp_fn(xnew)

        data_new = pd.DataFrame(ynew, index=xnew).reset_index()
        data_new.columns = ['Date',temp_df.name]
        data_new['Date'] = pd.to_datetime(data_new['Date'],unit='s').copy()
        smoothed_data = smoothed_data.merge(data_new, on='Date', how='outer')

    smoothed_data['Date'] = smoothed_data['Date'].apply(lambda x: x.date())
    smoothed_data = smoothed_data.set_index('Date')

    return smoothed_data



# [2] Create an empty backbone dataset that has all the dates of the studied
#    period. For each date, there are 4 Sources and 2 Sides
#    We shall use this dataset as a backbone frame to merge the relevant data
#    with and plot later. Nan values will be ignored by the plotting function

start_date = datetime.strptime("2023-10-07", "%Y-%m-%d")
end_date   = datetime.strptime("2024-10-07", "%Y-%m-%d")

date_list = pd.date_range(start_date, end_date, freq='D')

dates=[]
sources=[]
sides = []
for date_i in date_list:
    for src in ['Al Jazeera English', 'BBC', 'CNN Wire', 'The New York Times']:
        for side in ['Palestine','Israel','other']:
            dates.append(date_i)
            sources.append(src)
            sides.append(side)

df_main = pd.DataFrame({"Date":dates, "Source":sources, "Side_new":sides})



# [3] Initialize the plot parameters
figsize_x        = 40 

figsize_y        = 50

event_label_font = 40

plot_font        = 40

fig0, ax0 = plt.subplots(4,1,figsize = (figsize_x,figsize_y), sharey=True, sharex = True)


# [4] Get the count of articles published per day per Source 
df_tot_art_count = df_primary.groupby(['Date','Source'])['Article_ID'].nunique().reset_index()


# [5] Loop over the Sources to generate the data relevant to each and plot the
#     equivalent lineplot for that Source.

list_averages = []

for i, src_i in enumerate(list(dict_sources.keys())):

    
    # [5.1] Generate the Source's plotting data
    
    # -  create a copy of the backbone dataframe for our plotting purposes [5.1.0]
    df_lplot = df_main.copy()

    df_lplot = df_lplot.drop_duplicates(["Date","Source"]).copy()

    df_lplot = df_lplot.drop("Side_new", axis=1).copy()

    # -  create a filtered by Source copy of the CVN response data 
    df_src = df_cs[df_cs['Source']==src_i].copy()

    # -  loop over Instances of both Sides
    for side_i in ["Palestine","Israel"]:

        # -  [5.1.1] further filter the CVN response data by Side 
        df_src_side = df_src[df_src['Side_new']==side_i].copy()


        # -  [5.1.2] count the number of articles that have at least one CVN 
        #            this gives the daily count of CVNs per Side per Source
        df_src_side_daily_count = df_src_side.groupby(['Date','Source'])['Article_ID'].nunique().reset_index()
        df_src_side_daily_count = df_src_side_daily_count.rename(columns={"Article_ID":"Daily_Articles"})


        # -  [5.1.3] count the total number daily of articles published per Source
        df_src_tot_count = df_tot_art_count[df_tot_art_count['Source']==src_i].copy()
        df_src_tot_count = df_src_tot_count.rename(columns={"Article_ID":"Tot_Daily_Articles"})


        # -  [5.1.4] calculate the daily percentage of Articles per Side per Source  
        #    example: X% of the articles published by NYT on 7 Oct 2023 contained
        #             at least one Israeli CVN
        df_src_tot_count = df_src_tot_count.merge(df_src_side_daily_count,on=['Date','Source'],how='left')
        df_src_tot_count['Daily_Percent'] = (100* df_src_tot_count['Daily_Articles'] / df_src_tot_count['Tot_Daily_Articles']).round(2)
        df_src_tot_count['Daily_Percent'] = df_src_tot_count['Daily_Percent'].fillna(0)

        # -  [5.1.5] simplify the resulting output  
        df_plot_6 = df_src_tot_count[['Date', 'Source', 'Daily_Percent']].copy()
        df_plot_6 = df_plot_6.rename(columns = {"Daily_Percent":side_i})


        # [5.1.6] merge the df from [5.1.5] with the empty backbone dataset from [5.1.0]
        df_lplot = df_lplot.merge(df_plot_6, on=['Date','Source'], how='left')


    # [5.2] Caluclate the diff between the 2 Sides CVN Daily Percentages calculated above
    df_lplot['Pal_diff_Isr'] = df_lplot['Palestine'] - df_lplot['Israel']
    df_lplot = df_lplot.dropna(subset=['Pal_diff_Isr'])
    df_lplot = df_lplot.drop(["Palestine","Israel"], axis=1).copy()


    # [5.3] Group the data so that we end up having the mean of the percentage 
    #       difference every 6 days
    df_lplot = df_lplot.groupby([pd.Grouper(key='Date', freq='6D')])['Pal_diff_Isr'].mean().reset_index().copy()

    df_lplot = df_lplot.set_index('Date')


    # [5.4] Smooth out data for plotting purposes
    df_plot_6_reshaped_smooth = smooth_plot(df_lplot)


    # [5.5] Calculate the average Percentage Diff for the given Source
    avg_line = df_plot_6_reshaped_smooth['Pal_diff_Isr'].mean()
    list_averages.append(avg_line)
    
    
        
    # [5.6] Plot the vertical war event lines
    
    for _, row in df_events.iterrows():

        if (i == 0) & (row['Affected']=='Palestine'):
            ax0[i].text(x        = row['Label_Date']- timedelta(days=3),
                        y        = 135,
                        s        = row['Caption'],
                        va       = "bottom",
                        ha       ='left',
                        rotation = 'vertical',
                        fontsize = event_label_font,
                        color    = dict_colors[row['Affected']]
                        )


        if (i == 3) & (row['Affected']=='Israel'):
            ax0[i].text(x        = row['Label_Date']- timedelta(days=3),
                        y        = -125,
                        s        = row['Caption'],
                        va       = "top",
                        ha       ='left',
                        rotation = 'vertical',
                        fontsize = event_label_font,
                        color    = dict_colors[row['Affected']]
                        )


        ax0[i].axvline(x=row['Date'], color=dict_colors[row['Affected']], ls="dashed")


    # [5.7] Plot the lineplots

    sns.set_theme(rc={"figure.dpi": dpi})

    sns.set_style("whitegrid", {'axes.grid' : False})

    plot_i = sns.lineplot(
                 data=df_plot_6_reshaped_smooth,
                 palette= dict_colors,
                 linewidth=7,
                 #marker='o',
                 dashes=False,
                 legend = False,
                 ax = ax0[i]
                )

    
    # [5.7.1] plot the y=0 horizontal Line
    plot_i.axhline(y = 0, color = 'lightgrey', linestyle = 'dashdot')
    

    # [5.7.2] remove plot boundaries (top and right)
    sns.despine()


    # [5.7.3] update the title
    plot_i.set_title(dict_sources[src_i], fontsize = 16, y=1.03, fontweight='bold')


    # [5.7.4] remove x and y axis labels
    plot_i.set_xlabel('', fontsize = 4)
    plot_i.set_ylabel('', fontsize = plot_font)


    # [5.7.5] update label ticks font size
    ax0[i].tick_params(axis='x',labelsize = plot_font, labelrotation = 0)
    ax0[i].tick_params(axis='y',labelsize = plot_font, labelrotation = 0)


    # [5.7.6] update min and max yaxis values
    ax0[i].set_ylim(ymin = -100, ymax = 100)


    # [5.7.7] color the upper half of the plot green
    ax0[i].axhspan(ymin=0,  ymax=100, color=dict_colors['Palestine'], alpha=0.25)


    # [5.7.8] color the lower half of the plot blue
    ax0[i].axhspan(ymin=-100, ymax=0, color=dict_colors['Israel'], alpha=0.25)


    # [5.7.9] create a main yaxis label for the 4 plots
    y_axis_label = "% articles mentioning Palestinian casualties - % articles mentioning Israeli casualties"
    fig0.supylabel(y_axis_label, fontsize = plot_font+10, fontweight='bold', y=0.5, x=-0.01)


    # [5.7.10] update the x axis to properly display the dates
    ax0[i].xaxis.set_major_locator(mdates.MonthLocator())
    ax0[i].xaxis.set_major_formatter(mdates.DateFormatter('%b %y'))


    # [5.7.11] tighten the plot layout and export
    plt.tight_layout()
    
    

# [5.8] Export Final Plot and results

print("\n   The reported avergaes are:",[round(x,1) for x in list_averages])

plt.savefig(path_report + 'Supp Fig 6 - Disparity in casualty reporting across media sources' + '.svg', bbox_inches="tight", pad_inches=0.3)



# %% Supp Tab 6: Label Counts & Percent

print("\nGenerating Supp Tab 6")

# The CVN response Data had a "Statistics Type" column which basically
# identified the type of harm that the CVN points to, such as "Killed", 
# "Injured", "Displacement and Refugees" and so forth

# We manually went over each label and clustered them into these main groups:
# 'Casualties', 'Other', 'At risk and affected groups', 'Missing and Non-Casualty Victims',
# 'Displacement and Refugees', 'Imprisonment and Detention', 
# 'Deprivation, Malnutrition and Hunger', 'remove' (noise)
# 'Health and Medical Conditions', 'Humanitarian Aid & Dependence'

# The code below simply creates a dictionary that maps the CVN instance's
# Statistic Type to one of the Labels above



# [1] Import and Process the Statistics Types to Label dataset 
#     the resulting output should be a simple dataset of 2 columns:
#     "Statistic Type" that maps to one of the "Labels"
stat_types_labels = pd.read_excel(stat_label_categ_path)

stat_types_labels = stat_types_labels.fillna(" ")

stat_types_labels['Label'] = stat_types_labels.apply(lambda x: [x['Label_1']]+[x['Label_2']]+[x['Label_3']], axis=1)

stat_types_labels['Label'] = stat_types_labels['Label'].apply(lambda x: [j for j in x if j!= " "])

labels_dict = stat_types_labels.explode('Label').copy()

labels_dict = labels_dict[['Statistics Type', 'Label']].dropna().copy()

labels_dict['Label'] = labels_dict['Label'].apply(lambda x: x.strip())



# [2] Modify the CVN response data to include a Label column using the dictionary
# from the step above, and for table production purposes, we limit the columns
# to those outlined below

df_cs_sl = df_cs.copy()

temp_cols =['Article_ID', 'Statistics Type','Side_new', 'Source']

df_cs_sl_label = df_cs_sl[temp_cols].merge(labels_dict, on='Statistics Type', how='left')



# [3] Count num of CVN instances per Label per Side per Source 
#     Example: AJE pubslished 6346 "Casualties" CVN instances mentioning Pal side

df_supp_tab_6 = df_cs_sl_label.groupby(['Source','Side_new','Label'])['Article_ID'].count().reset_index()

df_supp_tab_6 = df_supp_tab_6.sort_values(['Source','Side_new', 'Article_ID'], ascending = [True, False, False])

df_supp_tab_6 = df_supp_tab_6.reset_index(drop=True)

df_supp_tab_6 = df_supp_tab_6.rename(columns = {'Article_ID':"Instances"})



# [4] Count total num of CVN instances per Side per Source (so we can calculate the %) 
df_supp_tab_6_total = df_cs_sl_label.groupby(['Source', 'Side_new'])["Article_ID"].count().reset_index()

df_supp_tab_6_total = df_supp_tab_6_total.rename(columns = {'Article_ID':"Total_Instances"})



# [5] Add the total counts from [4] to the label counts from [3]
df_supp_tab_6 = df_supp_tab_6.merge(df_supp_tab_6_total, on= ['Source','Side_new'], how = 'left' )



# [6] Calculate the percentage of Label instances of total instances, per source
df_supp_tab_6['Percent_Instances'] = (100 * df_supp_tab_6['Instances'] / df_supp_tab_6['Total_Instances']).round(1)



# [7] Export Output
title_tab_6 = "Supp Tab 6 - Distribution of CVNs by Type for Palestine and Israel across the four Media Outlets"

df_supp_tab_6.to_excel(path_report+ title_tab_6 + ".xlsx", index = False)




# %% Fig 3A: Count CVN Articles - Barplot

print("\nGenerating Fig 3A")


# [1] Data Preparation

# [1.1] Count the total num of articles 
df_total_art_count = df_primary.groupby('Source')['Article_ID'].count().reset_index()

df_total_art_count['Side_new'] = 'Total'

df_total_art_count = df_total_art_count.rename(columns = {'Article_ID' : 'Article_Count'})



# [1.2] Count total num of articles that contain at least 1 CVN instance 
df_cs_all_labels = df_cs.groupby(["Source", "Side_new"])['Article_ID'].nunique().reset_index()

df_cs_all_labels = df_cs_all_labels.rename(columns={"Article_ID":"Article_Count"})

df_cs_all_labels = df_cs_all_labels.sort_values(['Source','Side_new'], ascending = [True, False])



# [1.3] Merge the dataset [1.1] and [1.2]
keep_cols = ['Source', 'Side_new', 'Article_Count']

df_fig_3a = pd.concat([df_total_art_count, df_cs_all_labels[keep_cols]])



# [1.4] Sort the data for plotting purposes
df_fig_3a = df_fig_3a.sort_values(by=['Side_new'], ascending=False)



# [1.5] Replace the Source names with their abbreviations
df_fig_3a['Source'] = df_fig_3a['Source'].apply(lambda x: dict_sources[x])



# [1.6] Rename Sides for plotting in different colors
dict_legend = {'Total':'Total num of articles',
               'Palestine':'Articles with CVN about Palestine',
               'Israel': 'Articles with CVN about Israel'}


df_fig_3a['Side_new'] = df_fig_3a['Side_new'].apply(lambda x: dict_legend[x])



# [2] Plot the Barplot

fig3, ax3 = plt.subplots(1,1,figsize = (14,5))

sns.set_theme(rc={"figure.dpi": dpi})

sns.set_style("whitegrid", {'axes.grid' : False})

sns.set_color_codes("pastel")

sns.barplot(
            data=df_fig_3a,
            y='Source',
            x= 'Article_Count',
            orient="h",
            hue='Side_new',
            legend = True,
            palette= dict_colors,
            width = 0.7,
            )


sns.despine()


# [3] Annotate and tweak the plot

# -  add labels for each bar
for container, bar_color in zip(ax3.containers,df_fig_3a['Side_new'].unique() ):

    ax3.bar_label(container, color = dict_colors[bar_color], padding=3, fontsize = 11)


# -  tweak the axes and legend
plt.ylabel('')

plt.yticks(fontsize=6)

plt.xlabel('number of articles', fontweight='bold', labelpad=10, fontsize=12)

plt.legend(title="")

ax3.legend(bbox_to_anchor=(0.5, -0.25), loc='lower center', borderaxespad=0, ncol=4, fontsize=12)

plt.tight_layout()


# [4] Export the plot
title_Fig_3A = "Fig 3A - Total published articles against subsets containing at least one CVN about Palestine or Israel"

plt.savefig(path_report + title_Fig_3A + '.svg', bbox_inches="tight", pad_inches=0.1)



# %% Baseline Plots

# %%% Generate Data
print("\nGenerating Baseline Data")

# The code below generates the data required for plotting the Baseline lineplots

# The code starts by generating the data, combining it with the actual counts,
# and then uses it to plot Supp Fig 7 and Fig 3B


print("\nGenerating Baseline Data & Plots")

# [1] Filter the CVN data to keep those with "Casualties" label only
df_cs_casualty = df_cs_sl_label[df_cs_sl_label['Label'] == 'Casualties'].copy()



# [2] Add back the "Date" column from the original primary dataset using the 
#     "Article_ID" column
df_cs_casualty = df_cs_casualty.merge(df_primary[['Article_ID','Date']], on = 'Article_ID', how = 'left').copy()



# [3] Create a copy dataset 
df_base = df_cs_casualty.copy()



# [4] Replace the Source full name with an abbreviation instead 
#     (Al Jazeera English => AJE)
df_base['Source']   = df_base['Source'].apply(lambda x: dict_sources[x] if pd.notna(x) else x)



# [5] For the purpose of this dataset, we need the Side (Palestine/Israel) to 
#     be Pal/Isr
df_base['Side_new'] = df_base['Side_new'].apply(lambda x: x[:3])



# [6] Create a parallel copy of the data to determine the total number of CVN 
# instances per Source per 7 Days

# -  group data
df_base_tot = df_base.groupby([pd.Grouper(key='Date', freq='7D'), 'Source'])['Article_ID'].count().reset_index()#.unstack().unstack()

# -  create a column to include the Source + Side
df_base_tot['Source_Side'] = df_base_tot['Source'] + " Total Actual Mentions"



# [7] Modify the dataset from [3] to include the same Source-Side column as 
#     in [6]
df_base['Source_Side'] = df_base['Source'] + " " + df_base['Side_new'] + " Actual Mentions"



# [8] Group the data to count the number of CVNs per Source-Side
df_base = df_base.groupby([pd.Grouper(key='Date', freq='7D'), 'Source_Side'])['Article_ID'].count().reset_index()#.unstack().unstack()



# [9] Combine both datasets [6] and [7] 
df_base = pd.concat([df_base, df_base_tot])



# [10] Rearrange the dataset [9] so that we have the Source-Side values as the columns
df_base = df_base.pivot(index='Date', columns = 'Source_Side', values = 'Article_ID')



# [11] Minor adjustments to the final product
df_base = df_base.sort_values("Date")

df_base = df_base.reset_index()

df_base = df_base.rename(columns = {"Date":"start date"})



# [12] Import the actual reported casualties
df_actual_casualties = pd.read_csv(path_actual_casualties,
                                   usecols=['Start date', 'end date', 
                                            'Pal Total Killed', 'Pal Total injured',
                                            'Isr Total killed', 'Isr Total injured'])

df_actual_casualties = df_actual_casualties.rename(columns = {"Start date":"start date"})

df_actual_casualties['start date'] = pd.to_datetime(df_actual_casualties['start date'])

df_actual_casualties['end date'] = pd.to_datetime(df_actual_casualties['end date'])



# [13] Combine dataset from [11] which contains the weekly number of CVN mentions  
# per Source-Side and dataset from [12] whcih contains the actual reported weekly 
# casualties to produce the Baseline dataset
df = df_base.merge(df_actual_casualties, on='start date',how='left')



# %%% Supp Fig 7
print("\nGenerating Supp Fig 7")


# This plot provides a Baseline comparison of the expected versus actual number 
# of casualtyrelated CVN mentions for each news outlet over time.
# It illustrates the percentage difference between the expected (baseline) and 
# actual mentions for Palestinians and Israelis in each outlet

cols = ['Pal Total Killed','Pal Total injured', 'Isr Total killed', 'Isr Total injured','AJE Pal Actual Mentions', 'AJE Isr Actual Mentions',
       'AJE Total Actual Mentions', 'NYT Pal Actual Mentions','NYT Isr Actual Mentions', 'NYT Total Actual Mentions','CNN Pal Actual Mentions', 'CNN Isr Actual Mentions',
       'CNN Total Actual Mentions', 'BBC Pal Actual Mentions','BBC Isr Actual Mentions', 'BBC Total Actual Mentions']

df[cols] = df[cols].replace(',', '', regex=True).astype(int)

df['Total Casualties'] = df['Pal Total Killed'] + df['Pal Total injured'] + df['Isr Total killed'] + df['Isr Total injured']
df['Pal Casualties'] = df['Pal Total Killed'] + df['Pal Total injured']
df['Isr Casualties'] = df['Isr Total killed'] + df['Isr Total injured']

df['new event'] = df['Total Casualties'] > 2 * df['Total Casualties'].shift(1)
df['new event'] = df['Pal Total Killed'] > 2 * df['Pal Total Killed'].shift(1)
df['new event'] = df['Pal Total injured'] > 2 * df['Pal Total injured'].shift(1)
df['new event'] = df['new event'].astype(int)  # Convert boolean to 1 and 0
df.loc[0,'new event']=2 #start of war

#print(df.shape)
#df.head()

"""#Model with weekly mention values as a baseline"""

outlets = ["CNN","BBC",'AJE','NYT']
media = df.copy()

for m in outlets:
    #print(m)

    media['k'] = media[m+' Total Actual Mentions'] / (media['Pal Total Killed'] + media['Pal Total injured'] + media['Isr Total killed'] + media['Isr Total injured'])

    media['Pal Mt'] = media.k*media['Pal Total Killed'] + media.k*media['Pal Total injured']
    media['Isr Mt'] = media.k*media['Isr Total killed'] + media.k*media['Isr Total injured']

    # Double the 'Pal Mt' values where 'new event'
    media['new Pal Mt'] = media['Pal Mt']
    media.loc[df['new event'] == 1, 'new Pal Mt'] *= 2

    #decay effect of 10% (the 0.9)
    for i in range(0,53):
      for j in range(0,i+1):
        if (j==0) and (i==0):
          media.loc[i,'Pal Mt_decay'] = media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] = media.loc[j,'Isr Mt']*0.8**(i-j)
        elif j==0:
          media.loc[i,'Pal Mt_decay'] = media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] = media.loc[j,'Isr Mt']*0.8**(i-j)
        else:
          media.loc[i,'Pal Mt_decay'] += media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] += media.loc[j,'Isr Mt']*0.8**(i-j)

    #normalize s = (Pal Mt_decay / Total Mt_decay), and then s*Total Mt
    media['Pal s'] = media['Pal Mt_decay'] / (media['Pal Mt_decay']+media['Isr Mt_decay'])
    media[m+' Pal Baseline'] = (media['Pal Mt']+media['Isr Mt'])*media['Pal s']

    media['Isr s'] = media['Isr Mt_decay'] / (media['Pal Mt_decay']+media['Isr Mt_decay'])
    media[m+' Isr Baseline'] = (media['Pal Mt']+media['Isr Mt'])*media['Isr s']




# Generate a list of weekly dates starting from Oct 7, 2023
start_date = pd.to_datetime('2023-10-07')
date_range = [start_date + pd.Timedelta(weeks=i) for i in range(53)]

media.index = range(1, len(media) + 1)

# Assuming 'media' is your DataFrame
fig, ((ax1, ax3), (ax5, ax7)) = plt.subplots(2, 2, figsize=(20, 12))

def smooth_data(data):
    # Apply a moving average
    window_size = 2
    smoothed_data = data.rolling(window=window_size, center=True).mean()
    return smoothed_data

def plot_data(ax1, m, is_second_row, is_first_column, is_second_column):

    l1, = ax1.plot(media.index, media[m+' Pal Baseline'], label='Palestinian Expected Num of Mentions (Baseline)', color='#01933e', linestyle='--')
    l2, = ax1.plot(media.index, media[m+' Pal Actual Mentions'], label='Palenstinian Actual Num of Mentions', color='#01933e')
    l3, = ax1.plot(media.index, media[m+' Isr Baseline'], label='Israeli Expected Num of Mentions (Baseline)', color='#0038b8', linestyle='--')
    l4, = ax1.plot(media.index, media[m+' Isr Actual Mentions'], label='Israeli Actual Num of Mentions', color='#0038b8')


    # Create a second set of axes sharing the same x-axis
    ax2 = ax1.twinx()
    b1 = ax2.bar(x=media.index, height=media['Isr Casualties'], alpha=0.2, label='Total Israeli Casualties (Killed + Injured)')
    b2 = ax2.bar(x=media.index, height=media['Pal Casualties'], alpha=0.2, label='Total Palestinian Casualties (Killed + Injured)')

    # Add labels conditionally
    if is_first_column:
        ax1.set_ylabel('Total Weekly Mentions', fontsize=15)
    else:
        ax1.set_ylabel('')

    if is_second_column:
        ax2.set_ylabel('Total Weekly Casualties', fontsize=15)
    else:
        ax2.set_ylabel('')

    if is_second_row:
        ax1.set_xlabel("Week")
    else:
        ax1.set_xlabel("")

    ax1.tick_params(axis='x', which='major', labelsize=14)
    ax1.tick_params(axis='y', which='major', labelsize=14)
    ax2.tick_params(axis='y', which='major', labelsize=14)

    ax1.set_ylim(0, 350)
    ax1.set_xlim(0, 53)
    ticks = range(1, 54, 3)
    ax1.set_xticks(ticks)

    plt.title({
        'AJE': "AJE",
        'NYT': "NYT",
        'CNN': "CNN",
        'BBC': "BBC"
    }.get(m, m))

    return ax1.get_legend_handles_labels(), ax2.get_legend_handles_labels()

# Iterate over media sources and axes
for count, (m, ax, is_second_row, is_first_column, is_second_column) in enumerate(
    zip(['AJE', 'BBC', 'CNN', 'NYT'], [ax1, ax3, ax5, ax7], [False, False, True, True], [True, False, True, False], [False, True, False, True])):
    lines_and_labels, bars_and_labels = plot_data(ax, m, is_second_row, is_first_column, is_second_column)
    if count == 0:
        all_line_handles_labels = lines_and_labels
        all_bar_handles_labels = bars_and_labels

# Create legends using the handles and labels
line_handles, line_labels = all_line_handles_labels
bar_handles, bar_labels = all_bar_handles_labels

fig.legend(line_handles, line_labels, loc='upper center', bbox_to_anchor=(0.5, 0.06), ncol=4, fontsize=13)
fig.legend(bar_handles, bar_labels, loc='upper center', bbox_to_anchor=(0.5, 0.03), ncol=2, fontsize=13)

plt.tight_layout(rect=[0, 0.05, 1, 0.95])


plt.savefig(path_report + "Supp Fig 7 - Baseline comparison - Expected vs Actual Casualty CVNs mentions.svg", format="svg")



# %%% Fig 3B

print("\nGenerating Fig 3B")

# This code generates a lineplot that depicts the weekly proportion of expected
# mentions allocated to the Palestinian side (∆Pn) based on the baseline model, 
# shown for each of the four news outlets.

outlets = ['AJE','BBC','CNN','NYT']
media = df.copy()

for m in outlets:
    #print(m)

    media['k'] = media[m+' Total Actual Mentions'] / (media['Pal Total Killed'] + media['Pal Total injured'] + media['Isr Total killed'] + media['Isr Total injured'])

    media['Pal Mt'] = media.k*media['Pal Total Killed'] + media.k*media['Pal Total injured']
    media['Isr Mt'] = media.k*media['Isr Total killed'] + media.k*media['Isr Total injured']

    # Double the 'Pal Mt' values where 'new event'
    media['new Pal Mt'] = media['Pal Mt']
    media.loc[df['new event'] == 1, 'new Pal Mt'] *= 2

    #decay effect of 10% (the 0.9)
    for i in range(0,53):
      for j in range(0,i+1):
        if (j==0) and (i==0):
          media.loc[i,'Pal Mt_decay'] = media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] = media.loc[j,'Isr Mt']*0.8**(i-j)
        elif j==0:
          media.loc[i,'Pal Mt_decay'] = media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] = media.loc[j,'Isr Mt']*0.8**(i-j)
        else:
          media.loc[i,'Pal Mt_decay'] += media.loc[j,'new Pal Mt']*0.6**(i-j)
          media.loc[i,'Isr Mt_decay'] += media.loc[j,'Isr Mt']*0.8**(i-j)

    #normalize s = (Pal Mt_decay / Total Mt_decay), and then s*Total Mt
    media['Pal s'] = media['Pal Mt_decay'] / (media['Pal Mt_decay']+media['Isr Mt_decay'])
    media[m+' Pal Baseline'] = (media['Pal Mt']+media['Isr Mt'])*media['Pal s']

    media['Isr s'] = media['Isr Mt_decay'] / (media['Pal Mt_decay']+media['Isr Mt_decay'])
    media[m+' Isr Baseline'] = (media['Pal Mt']+media['Isr Mt'])*media['Isr s']

    media[m+' Pal Baseline Perc'] = media[m+' Pal Baseline'] / (media[m+' Pal Baseline']+media[m+' Isr Baseline'])*100
    media[m+' Isr Baseline Perc'] = media[m+' Isr Baseline'] / (media[m+' Pal Baseline']+media[m+' Isr Baseline'])*100

    media[m+' Pal Actual Perc'] = media[m+' Pal Actual Mentions'] / (media[m+' Total Actual Mentions'])*100
    media[m+' Isr Actual Perc'] =  media[m+' Isr Actual Mentions'] / (media[m+' Total Actual Mentions'])*100

    media[m+' Pal Diff'] = media[m+' Pal Baseline Perc'] - media[m+' Pal Actual Perc']
    media[m+' Isr Diff'] = media[m+' Isr Baseline Perc'] - media[m+' Isr Actual Perc']

    #print(media[m+' Pal Diff'].mean())
    #print(media[m+' Isr Diff'].mean())

    #print("#####################")

#media.head()

import matplotlib.pyplot as plt

# Assuming 'media' is your DataFrame
fig, ax1 = plt.subplots(figsize=(10, 6))  # Create one figure and axis

def plot_data(ax1, m,c):
    # Get the data
    data = media[m + ' Pal Diff']

    # Apply a moving average on the data to smooth
    window_size = 5
    smoothed_data = data.rolling(window=window_size, center=True).mean()

    # Plot the combined data
    ax1.plot(smoothed_data, label=r'$\Delta P_\text{' + m +'}$', linestyle='-', linewidth=2, color=c)

# Loop through each media outlet
for m,c in zip(['AJE','BBC','CNN','NYT'],['#F26E22','#000000','#CC0100','#9A9DA1']):
    plot_data(ax1, m,c)

# Add the horizontal line at y=0
ax1.axhline(y=0, color='grey', linestyle='--')

# Background shading: light blue for y > 0, light green for y < 0
ax1.axhspan(0, 100, facecolor='lightblue', alpha=0.2)
ax1.axhspan(-100, 0, facecolor='lightgreen', alpha=0.2)

# Annotate the top right corner with "Bias towards Israel"
ax1.text(0.95, 0.95, 'Bias towards Israel',
         verticalalignment='top', horizontalalignment='right',
         transform=ax1.transAxes, fontsize=12, color='darkblue')

# Annotate the bottom right corner with "Bias towards Palestine"
ax1.text(0.95, 0.05, 'Bias towards Palestine',
         verticalalignment='bottom', horizontalalignment='right',
         transform=ax1.transAxes, fontsize=12, color='darkgreen')

# Add labels and title
ax1.set_xlabel('Week', fontsize=11)
ax1.set_ylabel(r'$\Delta P_n$', fontsize=15)
ax1.set_ylim(-20, 60)
ax1.set_xlim(0, 52)
ticks = range(1, 54, 3)
ax1.set_xticks(ticks)
ax1.legend(loc="lower left", fontsize=14, ncol=2)

# Show the plot
plt.tight_layout()
plt.savefig(path_report + "Fig 3B - Baseline Plot.svg", format="svg")


   
# %% Supp Tab 9

print("\nGenerating Supp Table 9")

# [1] Import Cited-Sources CVN dataset
df_cited_sources = pd.read_excel(path_cvn_cited_source_resp)


# [2] Group the data to determine how many CVN instances were cited per 
# Side per Source - note that the "Cited" column had only Yes/No values
df_supp_tab_9 = df_cited_sources.groupby(['Source','Side_new','Cited'])['Instance_ID'].count().reset_index()

df_supp_tab_9.columns = ['Source', 'Side_new', 'Cited', 'Counts']



# [3] Get the total number of instances (Cited or Not) per Side per Source -
#     this shall be used to calculate the % later
temp_df   = df_cited_sources.groupby(['Source','Side_new'])['Instance_ID'].count().reset_index()

temp_df.columns = ['Source', 'Side_new', 'Total']



# [4] Merge the datasets from 2 and 3 so that we have the count of cited instances
#     in one column and the total num of instances in another, all per Side & Source
df_supp_tab_9 = df_supp_tab_9.merge(temp_df, on = ['Source', 'Side_new'], how = 'left')



# [5] Calculate the percentage of the cited instances of the total instances
df_supp_tab_9['Percent'] = (df_supp_tab_9['Counts']*100/df_supp_tab_9['Total']).round(1)



# [6] Filter the data to report the Cited counts
df_supp_tab_9 = df_supp_tab_9[df_supp_tab_9['Cited']=="Yes"].copy()

df_supp_tab_9 = df_supp_tab_9.sort_values('Side_new', ascending=False)


# [7] Rename columns
df_supp_tab_9 = df_supp_tab_9.rename(columns={'Counts':"Num of CVNs with a Reference",
                                              'Total':"Total Num of CVNs",
                                              'Side_new':'Side',
                                              'Percent':'Percentage'
                                              })



df_supp_tab_9 = df_supp_tab_9.drop(['Cited'], axis=1)

df_supp_tab_9 = df_supp_tab_9.sort_values(['Source','Side'],
                                          ascending = [True,False])

# [8] Calculate Ratios of Percentages

df_supp_tab_9["Ratio"] = np.nan
df_supp_tab_9.loc[df_supp_tab_9.index[::2], "Ratio"] = (
    df_supp_tab_9["Percentage"].iloc[::2].to_numpy().round(1)
    / df_supp_tab_9["Percentage"].iloc[1::2].to_numpy()
)
df_supp_tab_9["Ratio"] = df_supp_tab_9["Ratio"].fillna('')


# [9] Export the Output
title_supp_tab_9 = "Supp Tab 9 - Percentage of CVNs Reported with References Across Sources & Sides"

df_supp_tab_9.to_excel(path_report + title_supp_tab_9 + ".xlsx")



# %% Supp Tab 10-14

print("\nGenerating Supp Tab 10 to 14")

# [1] Import the CVN response data - fresh copy
df_cs_cd = pd.read_csv(path_cvn_resp)



# [2] Clean the dataset

# -  since an article full sentence can contain more than 1 CVN instance, 
#    then we need to keep a unique set of full sentences to count the phrases
df_cs_cd_uniq = df_cs_cd.drop_duplicates(['Article_ID','Side_new','Full_Sent']).copy()
   
# -  replace the full name of the sources with abbreviations
df_cs_cd_uniq['Source']    = df_cs_cd_uniq['Source'].map(dict_sources)

# -  convert the date from string to datetime
df_cs_cd_uniq['Date']      = pd.to_datetime(df_cs_cd_uniq['Date'], format = "%Y-%m-%d")

# -  clean the full sentences
df_cs_cd_uniq['Full_Sent'] = df_cs_cd_uniq['Full_Sent'].str.replace("-"," ")

df_cs_cd_uniq['Full_Sent'] = df_cs_cd_uniq['Full_Sent'].str.lower().str.replace(r"\s+", " ", regex=True)

# -  keep only relevant columns
df_cs_cd_uniq = df_cs_cd_uniq[['Date','Article_ID', 'Source', 'Side_new','Full_Sent']].copy()



# [3] Import & Preprocess the Critical Phrases dictionary
#     The dataset contains 2 columns: 
#        Phrases column: contains the Casting Doubt Phrases
#        CD_Type column: contains the type of the Casting Doubt Phrases 
#        The type may be "Source Doubting" or "Uncertainty in Numbers".
#     As such, the dataset acts as a dictionary that maps a Casting Doubt Phrase
#     to its Type - this will be used later in our analysis below.            


# -  import the dataset of highly critical phrases
dict_CD_phrases = pd.read_excel(cd_phrases_path)

# -  normalize the phrases
dict_CD_phrases['Original_Phrases'] = dict_CD_phrases['Phrases'].copy()

dict_CD_phrases.loc[:,'Phrases'] = dict_CD_phrases['Phrases'].str.replace(".","").str.replace(",","").str.replace("…","").str.strip().str.replace("-"," ").str.lower()
   

# -  as part of our further investigation, we later added the phrase "claim" to
#    the LLM list of identified Casting Doubt phrases
df_temp = pd.DataFrame({"Phrases":['claim'], 
                        "CD_Type":["Uncertainty in Numbers"],
                        "Original_Phrases":["claim"] })

dict_CD_phrases = pd.concat([dict_CD_phrases, df_temp]).copy()
   


# [4] Inspect each inique full sentence where an instance was detected to see
#     if it contains a Casting Doubt phrase

# -  this function takes as input a single sentence and a list of phrases and
#    returns a list of the detected phrases, if any, within that sentence
def find_phrases(sentence, phrases):
    
    sentence = sentence.replace("-"," ")
    
    found_phrases = [p for p in phrases if p.lower() in sentence.lower()]
    
    if len(found_phrases)>0:
        
        return found_phrases
    else:
        return None

# -  apply the find_phrases function to each and every sentence within the dataset
#    of CVN instances. This will result in a new column, "Phrases" where each
#    cell would have a list of all detected Casting Doubt phrases
df_cs_cd_uniq["Phrases"] = df_cs_cd_uniq["Full_Sent"].apply(find_phrases, phrases=dict_CD_phrases['Phrases'])

# -  since a sentence may contain more than one CVN and hence more than one
#    Casting Doubt phrase, thus we explode the Phrases column so that we can
#    inspect each casting doubt phrase on its own
df_cs_cd_uniq_res = df_cs_cd_uniq.dropna(subset=['Phrases']).explode('Phrases')


# -  apply the dictionary from [3[ to the detected phrases to determine their Type
df_cs_cd_uniq_res = df_cs_cd_uniq_res.merge(dict_CD_phrases, on = 'Phrases', how='left').copy()



# [5] Recall from [3] we manually added the phrase "claim" to the dictionary
#     based on our manual checking of the articles. Now, claim is a term that can
#     assume a non-Casting Doubt role, such as "the attack claimed 20 lives". As
#     such,we manually inspected the sentences containing the detected phrase 
#     "claim" and cleaned out those that are not used to Cast Doubt.


# -  divide the data from [4] into 2 datasets

# -     a. data without the "claim" containing sentences
filter_claims = df_cs_cd_uniq_res['Phrases']!='claim'

df_no_claim = df_cs_cd_uniq_res[filter_claims].copy()


# -     b. data with the "claim" containing sentences
df_claim = df_cs_cd_uniq_res[filter_claims].copy()

df_claim.to_excel(path_wip  + "Casting Doubt - Instances - Claim Sentences.xlsx")


# -  we manually inspected the df_claims output and flagged the valid instances 
df_claim = pd.read_excel(path_wip  + "Casting Doubt - Instances - Claim Sentences - Manually Classified - Done.xlsx")

filter_valid = df_claim['Flag']== 0

filter_claim = df_claim['Phrases']== "claim"

df_claim = df_claim[filter_valid & filter_claim].copy()


# -  we further cleaned the claims dataset, removing unwanted columns 
#    or any duplicated sentences (a precautionary step)
df_claim = df_claim.drop(['Unnamed: 0', 'Flag'], axis=1)

df_claim = df_claim.drop_duplicates(['Article_ID','Side_new', 'Full_Sent', 'Phrases'])

df_claim['Original_Phrases'] = 'claim'


# -  combine both datasets "a" and manually-inspected "b"
df_cs_cd_uniq_res = pd.concat([df_no_claim, df_claim]).copy()



# [6] Generate Casting Doubt phrase count reports per each Source

# -     create a backbone dataset that has all possible Date-Source-Side-CD Type 
#       combinations.
#       Example: for each day, we have 4 Sources x 2 Sides x 2 Types = 16 rows
#       Note that this is a simple empty dataset to cover all possible combinations

dates = pd.date_range(start="2023-10-07", end="2024-10-07", freq="D")

df_cd_main = pd.DataFrame(
    [(d, s, side, cd) for d in dates for s in news_sources for side in ['Palestine','Israel'] for cd in ['Source Doubting','Uncertainty in Numbers']],
    columns=["Date", "Source", "Side_new", 'CD_Type'])


# [7] Merge the dataset from [5] with that of [6] to add the Phrases (and their
#     full sentences) column
#     Example: On Oct 8,2023 the NYT published the following sentence:
#     "more than 600 israelis have reportedly been killed in attacks from 
#      Gaza since Saturday." - the Phrase used here is "reportedly" & its type 
#     is "Uncertainty in Numbers" as indicated by the added columns. 
#     Note that many of the rows would have a nan value since it is not necessary
#     that each day+source+side always had a Casting Doubt phrase published
#     at them

df_cd_main = df_cd_main.merge(df_cs_cd_uniq_res[['Date', 'Source', 'Side_new',
                                                 'Full_Sent','Phrases', 'CD_Type']], 
                              on=['Date','Source','Side_new','CD_Type'], how='left')



# [8] Merge the dataset from 7 with the Casting Doubt Dictionary to add only
#     the Original Phrases column instead of the normalized ones which we used
#     for better detection purposes and then keep only the relevant columns

df_cd_main_counts = df_cd_main.copy()

df_cd_main_counts = df_cd_main_counts.merge(dict_CD_phrases[['Phrases','Original_Phrases']],
                                            on = 'Phrases', how = 'left')

df_cd_main_counts = df_cd_main_counts[['Source', 'Side_new', 'Original_Phrases', 'Full_Sent']].copy()


# [9] Count the number of Phrases mentioned per Side per Source
df_temp = df_cd_main_counts.groupby(['Source','Side_new', 'Original_Phrases'])['Full_Sent'].count().reset_index()

df_temp = df_temp.rename(columns = {'Original_Phrases':"Phrases", 'Full_Sent':"CD_Counts"})


# [10] Create a backbone dataset that contains all possible combinations of 
#      Source (4) x Side (2) x Phrases (45) = 360 rows

df_bb = pd.DataFrame(
                        [(s, side, p) for s in news_sources for side in ['Palestine','Israel'] for p in dict_CD_phrases['Original_Phrases']],
                        columns=["Source", "Side_new", "Phrases"])


# [11] Merge Datasets from [10] and [11] so that we have a count of how many
#      times each of the phrases was mentined per Side per Source, with the nan
#      values resulting from the merger in step [10] set to zero as shown below
#      to indicate a zero count
#      Example: 
df_bb = df_bb.merge(df_temp, on = ['Source', 'Side_new', 'Phrases'], how = 'left')

df_bb = df_bb.fillna(0)


# [12] Create a backbone dataset that for now only has 2 Columns:
#      the "Orginal Phrases" and their "Type"
#      On its own, this dataset represents Supplementary Table 10 which shall 
#      exported as such. 

df_src_cd_counts = dict_CD_phrases[['Original_Phrases', 'CD_Type']].copy()

df_src_cd_counts = df_src_cd_counts.rename(columns = {'Original_Phrases':'Phrases'})

df_src_cd_counts = df_src_cd_counts.sort_values(['CD_Type','Phrases'])

df_supp_tab_10 = df_src_cd_counts.reset_index(drop=True)

df_supp_tab_10 = df_supp_tab_10.rename(columns = {"Phrases":"Doubt-Casting Phrase",
                                                  "CD_Type":"Category"})

title_supp_tab_10 = "Supp Tab 10 -  Final List of Doubt-Casting Phrases and Their Categories"

df_supp_tab_10.to_excel(path_report+ title_supp_tab_10 + ".xlsx")



# [13] Using the dataset crated in [12], we shall add the detected respected counts
#      once for every Source, and export these as Supp Tables 11,12,13 and 14
#      Each table will have the following columns in the end:
#         Phrases
#         Source - Total       (Phrase Counts)
#         Source - Palestine   (Phrase Counts)
#         Source - Israel      (Phrase Counts)
#         CD_Type              (Type of the Casting Doubt Phrase)

for tab_i, src_i in enumerate(news_sources):
    
    df_src_i_cd = df_bb[df_bb['Source']==src_i].copy()
    
    df_src_i_cd['temp_cols'] = df_src_i_cd['Source'] + " - " + df_src_i_cd['Side_new']

    
    df_src_i_cd = df_src_i_cd.pivot(index='Phrases', columns = 'temp_cols', values = 'CD_Counts')

    df_src_i_cd = df_src_i_cd.merge(dict_CD_phrases[['Original_Phrases','CD_Type']], left_on ='Phrases', right_on='Original_Phrases', how='left')

    df_src_i_cd = df_src_i_cd.rename(columns = {'Original_Phrases':'Phrases'})

    df_src_i_cd = df_src_i_cd.sort_values(['CD_Type','Phrases'])

    df_src_i_cd.loc[df_src_i_cd['CD_Type']=='Source Doubting', "{} - Israel".format(src_i)] = 0
    
    df_src_i_cd["{} - Total".format(src_i)] = df_src_i_cd[["{} - Palestine".format(src_i),"{} - Israel".format(src_i)]].sum(axis=1)

    
    df_src_i_cd = df_src_i_cd[['Phrases',
                           "{} - Total".format(src_i),
                           "{} - Palestine".format(src_i),
                           "{} - Israel".format(src_i), 
                           'CD_Type']].copy()
     

    # Export Phrase Counts per Source    
    title_i = "Supp Tab {} - Breakdown of Doubt-Casting Phrases in Casualty Reporting Sentences in {}.xlsx".format(tab_i+11,src_i)
    
    df_src_i_cd.to_excel(path_report + title_i)

    # Create one main table that contains the counts per all Sources for later analyses
    df_src_cd_counts = df_src_cd_counts.merge(df_src_i_cd, on = ['Phrases', 'CD_Type'])

    
# [14] Clean the resulting unified table
df_src_cd_counts = df_src_cd_counts.set_index('Phrases')    

reorder_cols = [i for i in df_src_cd_counts.columns if i!= "CD_Type"]

df_src_cd_counts = df_src_cd_counts[reorder_cols + ["CD_Type"]]

# export a copy to the past conflict analysis
df_src_cd_counts.to_csv(path_past_conflict_agg_data + "CVN - Casting Doubt Aggregate Data - 2023.csv")
 
# Note: the generated df_src_cd_counts dataset will be used to plot the
#       subplots of Fig 3C.


# %% Fig 3C


# %%% Barplot

print("\nGenerating Fig 3C - Barplot")

# The code below simply uses the data generated in the previous step to plot
# a bar plot displaying the total number of doubt-casting phrases per source

df_fig_3C_bar = df_src_cd_counts.T.iloc[[0,3,6,9],:].sum(axis=1).reset_index()

df_fig_3C_bar.columns = ['Source', 'Total_Count']

df_fig_3C_bar['Source'] = df_fig_3C_bar['Source'].apply(lambda x: x.split(" - ")[0].strip() )

fig_3C_bar, ax_3C_bar = plt.subplots(1,1,figsize = (5,8))

sns.barplot(data=df_fig_3C_bar,
            x='Source',
            y= 'Total_Count',
            orient="v",
            hue='Source',
            palette= dict_colors,
            width = 0.6)

plt.xticks(fontsize=4, rotation=90)
plt.xlabel('')
plt.ylabel('Total Count of Doubt Casting Phrases Used', fontsize=22,
           labelpad = 15, fontweight = 'bold')

plt.yticks(fontsize=22)

sns.despine()

plt.tight_layout()

plt.savefig(path_report + 'Fig 3C - Barplot - Total Num of Doubt-Casting Phrases per Source.svg')



# %%% Pie Charts

print("\nGenerating Fig 3C - Pie Chart")

# The code below uses the data generated in the previous step to plot
# Pie/Doughnut Charts that break down the Phrase counts by the type of 
# doubt-casting technique used by each outlet


# Prepare Imports
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Prepare Dataset: use data from previous step
df_polar_pie = df_src_cd_counts.groupby('CD_Type').sum()



keep_vals = ['Source Doubting (Palestine)',
             'Uncertainty in Num (Palestine)',
             'Uncertainty in Num (Israel)'
             ]


new_index = ['Source Doubting (Palestine)',
             'Uncertainty in Num (Palestine)',
             'Uncertainty in Num (Israel)'
             ]


df_pie_vals = pd.DataFrame()


for src in news_sources:
    
    vals = df_polar_pie.filter(regex= src, axis = 'columns').iloc[:,1:].values.flatten(order='F')

    vals  = np.delete(vals, 2)

    vals = pd.Series((vals*100/vals.sum()).round(0))

    df_pie_vals = pd.concat([df_pie_vals,vals], axis=1)

df_pie_vals.columns = news_sources

df_pie_vals.index   = keep_vals


df_pie_vals['exp']  = [0,0,0.1]

df_pie_vals['pos_x']  = [1,1,1]

df_pie_vals = df_pie_vals.reindex(new_index)




# Pie Chart: Loop over each source and plot its data
fig_3C_pie, ax_3C_pie = plt.subplots(2,2, figsize=(20, 6), dpi = 300)

fig_loc = [(0,0),(0,1),(1,0),(1,1)]

for plot_loc, src in zip(fig_loc, news_sources):

    data = df_pie_vals[[src, 'exp', 'pos_x']].copy()
    data = data[data[src]>0].copy()

    # identify location of pie plot based on source
    ii, jj = plot_loc

    # define size of the inner dohnut hole
    size = 0.4

    # get the source col of values
    vals = data[src]


    # colors
    pi_colors = {key: dict_colors[key] for key in list(vals.index) if key in dict_colors}


    # define order
    idx = np.arange(len(list(vals.index)))

    # determine wedge to explode
    explode_by = data['exp'].to_list()

    pi_side = list(vals.index)



    wedges, texts = ax_3C_pie[ii][jj].pie(
                list(vals),
                #labels = [str(round(j,1))+"%" for j in vals],
                #labeldistance = 0.65,
                #textprops={'color': 'white', 'fontsize': 10, 'fontweight':'bold'},
                radius=1,
                colors=pi_colors.values(),
                wedgeprops=dict(width=size, edgecolor='w', linewidth= 1),
                explode=explode_by,
                #hatch=data['hash'].tolist()
                )

    if len(wedges) == len(df_pie_vals):
        export_wedge = wedges

    ax_3C_pie[ii][jj].set(aspect="equal", title = src)

    ax_3C_pie[ii][jj].set_title(src, fontsize=8, loc='center', y=0.45)

    # add annotations
    bbox_props = dict(boxstyle="square,pad=0.2", fc="w", ec="k", lw=0.8)

    kw = dict(arrowprops=dict(arrowstyle="-", color="black", lw=0.8),
              bbox=bbox_props, zorder=0, va="center")


    # add preset multiples to space out the annotation text
    pos_x = data['pos_x'] .to_list()



    vals = list(vals)

    # plot the text within the boxes
    for i, p in enumerate(wedges):
        i_mod = i+1
        ang   = (p.theta2 - p.theta1)/2. + p.theta1
        y     = np.sin(np.deg2rad(ang))
        x     = np.cos(np.deg2rad(ang))

        horizontalalignment = {-1: "right", 1: "left"}[int(np.sign(x))]

        connectionstyle = f"angle,angleA=0,angleB={ang}"

        kw["arrowprops"].update({"connectionstyle": connectionstyle})

        # replace the 2 lines above with the line below to avoid issues
        # with the annotation lines
        # kw["arrowprops"].update({"connectionstyle": "arc3,rad=0.0"})

        ax_3C_pie[ii][jj].annotate(
                    #pi_side[i].split(" -")[0] +": "+ str(vals[i]),
                    str(int(vals[i]))+"%",
                    xy                  = (x, y),
                    xytext              = (1.5 * pos_x[i] * np.sign(x), 1.5*y),
                    horizontalalignment = horizontalalignment, **kw,
                    color               = pi_colors[pi_side[i]],
                    fontsize            = 18,
                    fontweight          = "bold"
                    )

# this code adds one main legend for all subplots, up center
fig_3C_pie.legend(export_wedge,
            list(df_pie_vals.index),
            loc = 'upper center',
            bbox_to_anchor = (0.5, -0.01),
            ncol = 3,
            fontsize = 16
            )


# Export the figure
plt.tight_layout()

plt.savefig(path_report + 'Fig 3C - Pie Chart - Casting Doubt Phrase Counts per Type per Source.svg', bbox_inches="tight")



#%% CVN Child Analysis

# %%% Supp Fig 8 and 9

print("\nGenerating Supp Fig 8 and 9")


# import the dataset of CVN response data that has a column
# containing the full sentences 

df_cs_cd = pd.read_csv(path_cvn_resp)

supp_tables = []

for fig_i, data_extent in enumerate([' - All Data', ' - Casualty Data' ]):

    
    # Prepare dataset for plotting
    df_child = df_cs_cd[(df_cs_cd['Is Child'] == 'Yes')&(df_cs_cd['Side_new'] != 'other')].copy()

    # prepare title for exporting figure
    title_supp_fig_i = "Supp Fig {} - Proportion of Articles Reporting Child-Related CVNs by Side and Media Source".format(fig_i+8)


    if data_extent == " - Casualty Data":

        # Keep only Casualties label CVNs
        df_child = df_child.merge(labels_dict, on='Statistics Type', how = 'left')
        df_child = df_child[df_child["Label"]=='Casualties'].copy()
        
        # Adjust title
        title_supp_fig_i = title_supp_fig_i + " for Casualties-related CVNs only"


    #"Articles with child-related CVNs (Palestine)", "Articles with no child-related CVNs (Palestine)

    # Define dictionaries to relabel the side column for the datasets below - legend plotting purposes
    relabel_side_dict_child     = {"Israel":'Articles with child-related CVNs (Israel)',
                                   "Palestine":'Articles with child-related CVNs (Palestine)',
                                   }

    relabel_side_dict_non_child = {"Israel":'Articles with no child-related CVNs (Israel)',
                                   "Palestine":'Articles with no child-related CVNs (Palestine)',
                                   }

    # CHILD ARTICLE COUNTS

    # Count of articles with at least 1 child count against total instances, per side per source
    df_fig4_child = df_child.groupby(["Source", "Side_new"])['Article_ID'].nunique().reset_index()
    df_fig4_child = df_fig4_child.rename(columns = {'Article_ID':'Child_Article_Count'})


    # plotting tweaks
    df_fig4_child = df_fig4_child.sort_values(["Source", "Side_new"], ascending=[True,False])
    df_fig4_child['Source'] = df_fig4_child['Source'].map(dict_sources)



    # TOTAL ARTICLE COUNTS

    # get the total article counts per side per source
    df_fig4_total = df_cs_cd.groupby(["Source", "Side_new"])['Article_ID'].nunique().reset_index()
    df_fig4_total = df_fig4_total.rename(columns = {'Article_ID':'Total_Article_Count'})

    # plotting tweaks
    df_fig4_total = df_fig4_total.sort_values(["Source", "Side_new"], ascending=[True,False])
    df_fig4_total['Source'] = df_fig4_total['Source'].map(dict_sources)



    # CALCULATE PERCENTAGES
    df_table_4 = df_fig4_child.merge(df_fig4_total, on=['Source','Side_new'])
    df_table_4['Percent'] = (100*df_table_4['Child_Article_Count'] / df_table_4['Total_Article_Count']).round(1)


    # relabel the side column
    df_fig4_child['Side_new'] = df_fig4_child['Side_new'].replace(relabel_side_dict_child)

    df_fig4_total['Side_new'] = df_fig4_total['Side_new'].replace(relabel_side_dict_non_child)



    # BARPLOTs: CHILD + TOTAL COUNTS
    fig4, ax4 = plt.subplots(1,1,figsize = (12,4))

    sns.barplot(data=df_fig4_total,
                y='Source',
                x= 'Total_Article_Count',
                orient="h",
                hue='Side_new',
                palette= dict_colors,
                width = 0.6,
                errorbar = None)

    sns.barplot(data=df_fig4_child,
                y='Source',
                x= 'Child_Article_Count',
                orient="h",
                hue='Side_new',
                palette= dict_colors,
                width = 0.6,
                errorbar = None)


    sns.despine()

    ax4.legend(bbox_to_anchor=(0.5, -0.45), loc='lower center', borderaxespad=0, ncol=2, fontsize=14)

    plt.xlabel('number of articles'+data_extent, fontweight='bold', labelpad=10, fontsize=12)

    plt.ylabel('')

    plt.yticks(fontsize=6)
    
    
    # EXPORT OUTPUT
    plt.savefig(path_report + title_supp_fig_i + '.svg', bbox_inches="tight", pad_inches=0.1)

    df_table_4 = df_table_4.rename(columns = {'Total_Article_Count':'Articles with CVNs'})

    if data_extent == ' - All Data':
        
        column_names = ['Media Source', 'Side', 
                        'Articles with Child CVNs',     
                        'Articles with CVNs',
                        'Percent Child CVNs']
    
        df_table_4.columns = column_names
    else:
        
        column_names = ['Media Source', 'Side', 
                        'Articles with Casualty-Related Child CVNs', 
                        'Articles with CVNs',
                        'Percent Casualty-Related Child CVNs']

        df_table_4.columns = column_names


    supp_tables.append(df_table_4)
    
    

  
# %%% Supp Tab 15 


print("\nGenerating Tab 15")


df1, df2 = supp_tables



df_supp_tab_15 = pd.merge(df1, df2, on=['Media Source', 
                                        'Side',
                                        'Articles with CVNs'], how="inner")

reorder_cols = [ 'Media Source', 
                 'Side', 
                 'Articles with Casualty-Related Child CVNs',
                 'Articles with Child CVNs', 
                 'Articles with CVNs',
                 'Percent Casualty-Related Child CVNs',
                 'Percent Child CVNs' ]


df_supp_tab_15 = df_supp_tab_15[reorder_cols].copy()

title_supp_tab_15 = "Supp Tab 15 - Child-related Mentions in Media Coverage of Palestine and Israel"

df_supp_tab_15.to_excel(path_report + title_supp_tab_15 + '.xlsx')



# %% Supp Fig 15

print("\nGenerating Supp Fig 15")


# Plot the CD Counts 

# -  Group CD Counts by Week (6 Days)

df_cd_main_grp = df_cd_main.groupby([pd.Grouper(key='Date', freq='6D'),'Source','Side_new','CD_Type'])['Phrases'].count()

df_cd_main_grp = df_cd_main_grp.rename("CD_Counts")

df_cd_main_grp = df_cd_main_grp.reset_index()

df_cd_main_grp['CD_Type_Side'] = df_cd_main_grp['CD_Type'] + " (" + df_cd_main_grp['Side_new'] + ")" 



# -  Fix Source Doubting - Israel Count to be 0 since all the phrases concern
# doubting Ham, not Isr.
cond_1 = df_cd_main_grp['CD_Type_Side'] == 'Source Doubting (Israel)'

df_cd_main_grp.loc[cond_1, 'CD_Counts'] = 0


# -  Plot the Counts per Source

plot_font = 20

fig5_1, ax5_1 = plt.subplots(4,1,figsize = (20,25), sharey=True, sharex = True)


for i, src_i in enumerate(news_sources):
    
    df_cd_cvn_src_i = df_cd_main_grp[df_cd_main_grp['Source']==src_i].reset_index(drop=True).copy()
    
    df_cd_plot = df_cd_cvn_src_i[['Date', 'CD_Type_Side', 'CD_Counts']].pivot(index="Date", columns="CD_Type_Side", values="CD_Counts")

    
    # Clean and Smooth the Plot
    df_cd_plot = df_cd_plot.drop(['Source Doubting (Israel)'],axis=1)
    
    df_cd_plot = smooth_plot(df_cd_plot)
    
    df_cd_plot = df_cd_plot.clip(lower = 0).copy()


    # Plot the Weekly aggregates 
    plot_i = sns.lineplot(data       = df_cd_plot,
                          
                          palette    = dict_colors,
                          linewidth  = 5,
                          dashes     = False,
                          legend     =(i == 0),
                          #legend    = False,
                          ax         = ax5_1[i]
                          )
    if i == 0:
        ax5_1[0].legend(
            bbox_to_anchor=(0.5, 1.1),
            loc="lower center",
            ncol     = 3,
            fontsize = plot_font,
            frameon=False
        )
    
    # remove plot boundaries (top and right)
    sns.despine()


    # update the title
    plot_i.set_title(src_i, fontsize = 6, y=1.03, fontweight='bold')


    # remove x and y axis labels
    plot_i.set_xlabel('', fontsize = 4)
    plot_i.set_ylabel('', fontsize = plot_font)


    # update label ticks font size
    #ax5_1[i].tick_params(axis='x',labelsize = plot_font, labelrotation = 45)
    #ax5_1[i].tick_params(axis='y',labelsize = plot_font, labelrotation = 0)

    ax5_1[i].tick_params(axis="both", labelsize=plot_font)

    plt.setp(ax5_1[i].get_xticklabels(), fontweight="bold", rotation=45)
    plt.setp(ax5_1[i].get_yticklabels(), fontweight="bold")

    # update min and max yaxis values
    #ax5_1[i].set_ylim(ymin = -100, ymax = 100)


    # create a main yaxis label for the 4 plots
    y_axis_label = "Weekly Count of Doubt Casting Phrases by Source, Side & Style"

    fig5_1.supylabel(y_axis_label, 
                     fontsize   = plot_font+10, 
                     fontweight ='bold', 
                     y = 0.5, 
                     x = 0)


    # update the x axis to properly display the dates
    ax5_1[i].xaxis.set_major_locator(mdates.MonthLocator())
    ax5_1[i].xaxis.set_major_formatter(mdates.DateFormatter('%b %y'))

    
    #plt.legend(title="")
    

    # tighten the plot layout and export
    plt.tight_layout()

    plt.savefig(path_report + 'Supp Fig 15 - Weekly share of CVN statements published in 2023-2024 that had Casting Doubt phrases.svg')



    
